version: "2"

volumes:
  mysql:

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile.development
    command: rails server --bind 0.0.0.0
    volumes:
      - ./:/srv/app
    ports:
      - 3000:3000
    depends_on:
      - mysql

  mysql:
    image: mysql:5.5
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
